### ISSUE TITLE
AzGovVizParallel.ps1 - ParserError: The '<' operator is reserved for future use.

### ISSUE THREAD

**Issue by WVDAdminTF** [JulianHayward/AzAPICall#37]
Hello,

While running the script I am getting this error.

PS C:\Users\Admin\Downloads> .\AzGovVizParallel.ps1 -ManagementGroupId bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Security warning
Run only scripts that you trust. While scripts from the internet can be useful, this script can potentially harm your
computer. If you trust this script, use the Unblock-File cmdlet to allow the script to run without this warning
message. Do you want to run C:\Users\Admin\Downloads\AzGovVizParallel.ps1?
[D] Do not run  [R] Run once  [S] Suspend  [?] Help (default is "D"): R
ParserError: C:\Users\Admin\Downloads\AzGovVizParallel.ps1:210
Line |
 210 |  … k Button--medium Button d-lg-none color-fg-inherit p-1">    <span cla …
     |                                                                ~
     | The '<' operator is reserved for future use.
PS C:\Users\Admin\Downloads>

Please refer to image too.
![error](https://user-images.githubusercontent.com/84956733/210334532-241aeb91-57fa-405b-971a-40e60cf565a4.jpg)

Regards,
WVDAdminTF

**Comment by JulianHayward** [comment]
@WVDAdminTF Hello, please log azGovViz errors at aka.ms/azgovviz  
This very much looks like a copy paste issue. Please try to clone the repo or download the zip  
<img width="262" alt="image" src="https://user-images.githubusercontent.com/45695032/210340154-5844a966-1f90-49f2-ad64-8df7a81c4456.png">

**Comment by WVDAdminTF** [comment]
Thank you so much, the Issue has been resolve after downloading the Zip file and executing it from the PWSH directory

Regards,
WVDAdminTF
