### ISSUE TITLE
Some 'writeMethod' and 'debugWriteMethod' are causing error while the initalization of AzAPICall

### ISSUE THREAD

**Issue by kaiaschulz** [JulianHayward/AzAPICall#38]
In some combinations of the `writeMethod` and `debugWriteMethod` the initialization of AzAPICall is failing and running into an error:
```POWERSHELL
Line |
1788 |  … rs'] += setHtParameters -AzAccountsVersion $AzAccountsVersion -gitHub …
     |                                               ~~~~~~~~~~~~~~~~~~
     | Cannot process argument transformation on parameter 'AzAccountsVersion'. Cannot convert value to type System.String.
  AzAPICall htParameters:

Name             Value
----             -----
writeMethod      Output
debugWriteMethod Output


  Create htParameters succeeded
 Get Az context
  Get Az context succeeded
WARNING:  Check Az context
WARNING:   Az context AccountId: ''
WARNING:   Az context AccountType: ''
InvalidOperation: C:\<Path>\Modules\AzAPICall\1.1.68\functions\AzAPICallFunctions.ps1:1817:61
Line |
1817 |  … accountType = $($AzAPICallConfiguration['checkContext'].Account.Type)
     |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property 'accountType' cannot be found on this object. Verify that the property exists and can be set.

WARNING:   Check Az context failed: Az context is not set to any Subscription
WARNING:   Set Az context to a subscription by running: Set-AzContext -subscription <subscriptionId> (run Get-AzSubscription to get the list of available Subscriptions). When done re-run the script
WARNING:   OR
WARNING:   Use parameter -SubscriptionId4AzContext - e.g. .\AzGovVizParallel.ps1 -SubscriptionId4AzContext <subscriptionId>
Exception: C:\<Path>\Modules\AzAPICall\1.1.68\functions\AzAPICallFunctions.ps1:1859:9
Line |
1859 |          Throw 'Error - check the last console output for details'
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Error - check the last console output for details
```

Regarding to this, I wrote a small script to analyze which of the possible 64 combinations are affected to identify them and improving the code:

TestCases | Method | Debug | Error | Host | Information | Output | Progress | Verbose | Warning
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | writeMethod | x |   |   |   |   |   |   |  
1 | debugWriteMethod | x |   |   |   |   |   |   |  
2 | writeMethod | x |   |   |   |   |   |   |  
2 | debugWriteMethod |   | x |   |   |   |   |   |  
3 | writeMethod | x |   |   |   |   |   |   |  
3 | debugWriteMethod |   |   | x |   |   |   |   |  
4 | writeMethod | x |   |   |   |   |   |   |  
4 | debugWriteMethod |   |   |   | x |   |   |   |  
5 | writeMethod | x |   |   |   |   |   |   |  
5 | debugWriteMethod |   |   |   |   | x |   |   |  
6 | writeMethod | x |   |   |   |   |   |   |  
6 | debugWriteMethod |   |   |   |   |   | x |   |  
7 | writeMethod | x |   |   |   |   |   |   |  
7 | debugWriteMethod |   |   |   |   |   |   | x |  
8 | writeMethod | x |   |   |   |   |   |   |  
8 | debugWriteMethod |   |   |   |   |   |   |   | x
9 | writeMethod |   | x |   |   |   |   |   |  
9 | debugWriteMethod | x |   |   |   |   |   |   |  
10 | writeMethod |   | x |   |   |   |   |   |  
10 | debugWriteMethod |   | x |   |   |   |   |   |  
11 | writeMethod |   | x |   |   |   |   |   |  
11 | debugWriteMethod |   |   | x |   |   |   |   |  
12 | writeMethod |   | x |   |   |   |   |   |  
12 | debugWriteMethod |   |   |   | x |   |   |   |  
13 | writeMethod |   | x |   |   |   |   |   |  
13 | debugWriteMethod |   |   |   |   | x |   |   |  
14 | writeMethod |   | x |   |   |   |   |   |  
14 | debugWriteMethod |   |   |   |   |   | x |   |  
15 | writeMethod |   | x |   |   |   |   |   |  
15 | debugWriteMethod |   |   |   |   |   |   | x |  
16 | writeMethod |   | x |   |   |   |   |   |  
16 | debugWriteMethod |   |   |   |   |   |   |   | x
17 | writeMethod |   |   | x |   |   |   |   |  
17 | debugWriteMethod | x |   |   |   |   |   |   |  
18 | writeMethod |   |   | x |   |   |   |   |  
18 | debugWriteMethod |   | x |   |   |   |   |   |  
19 | writeMethod |   |   | x |   |   |   |   |  
19 | debugWriteMethod |   |   | x |   |   |   |   |  
20 | writeMethod |   |   | x |   |   |   |   |  
20 | debugWriteMethod |   |   |   | x |   |   |   |  
21 | writeMethod |   |   | x |   |   |   |   |  
21 | debugWriteMethod |   |   |   |   | x |   |   |  
22 | writeMethod |   |   | x |   |   |   |   |  
22 | debugWriteMethod |   |   |   |   |   | x |   |  
23 | writeMethod |   |   | x |   |   |   |   |  
23 | debugWriteMethod |   |   |   |   |   |   | x |  
24 | writeMethod |   |   | x |   |   |   |   |  
24 | debugWriteMethod |   |   |   |   |   |   |   | x
25 | writeMethod |   |   |   | x |   |   |   |  
25 | debugWriteMethod | x |   |   |   |   |   |   |  
26 | writeMethod |   |   |   | x |   |   |   |  
26 | debugWriteMethod |   | x |   |   |   |   |   |  
27 | writeMethod |   |   |   | x |   |   |   |  
27 | debugWriteMethod |   |   | x |   |   |   |   |  
28 | writeMethod |   |   |   | x |   |   |   |  
28 | debugWriteMethod |   |   |   | x |   |   |   |  
29 | writeMethod |   |   |   | x |   |   |   |  
29 | debugWriteMethod |   |   |   |   | x |   |   |  
30 | writeMethod |   |   |   | x |   |   |   |  
30 | debugWriteMethod |   |   |   |   |   | x |   |  
31 | writeMethod |   |   |   | x |   |   |   |  
31 | debugWriteMethod |   |   |   |   |   |   | x |  
32 | writeMethod |   |   |   | x |   |   |   |  
32 | debugWriteMethod |   |   |   |   |   |   |   | x
33 | writeMethod |   |   |   |   | x |   |   |  
33 | debugWriteMethod | x |   |   |   |   |   |   |  
34 | writeMethod |   |   |   |   | x |   |   |  
34 | debugWriteMethod |   | x |   |   |   |   |   |  
35 | writeMethod |   |   |   |   | x |   |   |  
35 | debugWriteMethod |   |   | x |   |   |   |   |  
36 | writeMethod |   |   |   |   | x |   |   |  
36 | debugWriteMethod |   |   |   | x |   |   |   |  
37 | writeMethod |   |   |   |   | x |   |   |  
37 | debugWriteMethod |   |   |   |   | x |   |   |  
38 | writeMethod |   |   |   |   | x |   |   |  
38 | debugWriteMethod |   |   |   |   |   | x |   |  
39 | writeMethod |   |   |   |   | x |   |   |  
39 | debugWriteMethod |   |   |   |   |   |   | x |  
40 | writeMethod |   |   |   |   | x |   |   |  
40 | debugWriteMethod |   |   |   |   |   |   |   | x
41 | writeMethod |   |   |   |   |   | x |   |  
41 | debugWriteMethod | x |   |   |   |   |   |   |  
42 | writeMethod |   |   |   |   |   | x |   |  
42 | debugWriteMethod |   | x |   |   |   |   |   |  
43 | writeMethod |   |   |   |   |   | x |   |  
43 | debugWriteMethod |   |   | x |   |   |   |   |  
44 | writeMethod |   |   |   |   |   | x |   |  
44 | debugWriteMethod |   |   |   | x |   |   |   |  
45 | writeMethod |   |   |   |   |   | x |   |  
45 | debugWriteMethod |   |   |   |   | x |   |   |  
46 | writeMethod |   |   |   |   |   | x |   |  
46 | debugWriteMethod |   |   |   |   |   | x |   |  
47 | writeMethod |   |   |   |   |   | x |   |  
47 | debugWriteMethod |   |   |   |   |   |   | x |  
48 | writeMethod |   |   |   |   |   | x |   |  
48 | debugWriteMethod |   |   |   |   |   |   |   | x
49 | writeMethod |   |   |   |   |   |   | x |  
49 | debugWriteMethod | x |   |   |   |   |   |   |  
50 | writeMethod |   |   |   |   |   |   | x |  
50 | debugWriteMethod |   | x |   |   |   |   |   |  
51 | writeMethod |   |   |   |   |   |   | x |  
51 | debugWriteMethod |   |   | x |   |   |   |   |  
52 | writeMethod |   |   |   |   |   |   | x |  
52 | debugWriteMethod |   |   |   | x |   |   |   |  
53 | writeMethod |   |   |   |   |   |   | x |  
53 | debugWriteMethod |   |   |   |   | x |   |   |  
54 | writeMethod |   |   |   |   |   |   | x |  
54 | debugWriteMethod |   |   |   |   |   | x |   |  
55 | writeMethod |   |   |   |   |   |   | x |  
55 | debugWriteMethod |   |   |   |   |   |   | x |  
56 | writeMethod |   |   |   |   |   |   | x |  
56 | debugWriteMethod |   |   |   |   |   |   |   | x
57 | writeMethod |   |   |   |   |   |   |   | x
57 | debugWriteMethod | x |   |   |   |   |   |   |  
58 | writeMethod |   |   |   |   |   |   |   | x
58 | debugWriteMethod |   | x |   |   |   |   |   |  
59 | writeMethod |   |   |   |   |   |   |   | x
59 | debugWriteMethod |   |   | x |   |   |   |   |  
60 | writeMethod |   |   |   |   |   |   |   | x
60 | debugWriteMethod |   |   |   | x |   |   |   |  
61 | writeMethod |   |   |   |   |   |   |   | x
61 | debugWriteMethod |   |   |   |   | x |   |   |  
62 | writeMethod |   |   |   |   |   |   |   | x
62 | debugWriteMethod |   |   |   |   |   | x |   |  
63 | writeMethod |   |   |   |   |   |   |   | x
63 | debugWriteMethod |   |   |   |   |   |   | x |  
64 | writeMethod |   |   |   |   |   |   |   | x
64 | debugWriteMethod |   |   |   |   |   |   |   | x

The result of the tests shows that 21 combinations of the 64 test cases are affected:
1. Write-Error: writeMethod: Error; debugWriteMethod: Debug
2. Write-Error: writeMethod: Error; debugWriteMethod: Information
3. Write-Error: writeMethod: Error; debugWriteMethod: Error
4. Write-Error: writeMethod: Error; debugWriteMethod: Output
5. Write-Error: writeMethod: Error; debugWriteMethod: Verbose
6. Write-Error: writeMethod: Error; debugWriteMethod: Warning
7. Write-Error: writeMethod: Error; debugWriteMethod: Host
8. Write-Error: writeMethod: Error; debugWriteMethod: Progress
9. Write-Error: writeMethod: Output; debugWriteMethod: Output
10. Write-Error: writeMethod: Output; debugWriteMethod: Debug
11. Write-Error: writeMethod: Output; debugWriteMethod: Verbose
12. Write-Error: writeMethod: Output; debugWriteMethod: Information
13. Write-Error: writeMethod: Output; debugWriteMethod: Progress
14. Write-Error: writeMethod: Output; debugWriteMethod: Warning
15. Write-Error: writeMethod: Output; debugWriteMethod: Host
16. Write-Error: writeMethod: Debug; debugWriteMethod: Error
17. Write-Error: writeMethod: Progress; debugWriteMethod: Error
18. Write-Error: writeMethod: Verbose; debugWriteMethod: Error
19. Write-Error: writeMethod: Warning; debugWriteMethod: Error
20. Write-Error: writeMethod: Information; debugWriteMethod: Error
21. Write-Error: writeMethod: Host; debugWriteMethod: Error

The different methods of writing are needed for a customization of the output.
Some of the Azure services, e.g. Automation Account, won't display `Write-Host`.

**Comment by JulianHayward** [comment]
awesome :) @kaiaschulz thanks - merged and published to psGal
