### ISSUE TITLE
Error when setting context

### ISSUE THREAD

**Issue by AsbjornNielsen** [JulianHayward/AzAPICall#43]
Hi.

I use AzAPICall as part of AzGovViz.
Using AzGovViz, I export data from several tenants, however, one of the tenants suddenly required the SubscriptionId4AzContext, which I have then provided. However, the addition of SubscriptionId4AzContext makes a Set-AzContext fail with "Please provide a valid tenant or a valid subscription." as if it can't find the subscription.
![image](https://github.com/JulianHayward/AzAPICall/assets/9654937/462a5163-e09d-46d9-9f71-034d6216f8db)

AzAPICall tries to Set-AzContext at line 1834 and then throws. This could of course be because I give it a wrong subscription ID but just before the Set-AzContext it tests the subscription at line 1830, using testSubscription, which correctly finds the subscription. I also verified that the ID it checked is the correct one.

I have tried logging in in Azure using the app registration that I use for the pipeline and I can switch between all necessary subscriptions.
I can't find a reason why it will not set the context.

**Comment by AsbjornNielsen** [comment]
Yes we use self hosted agents in general. However, I just tested it with the "normal" azure pipelines agents and got the same result. "Please provide a valid tenant or a valid subscription".

I also tested running AzGovViz - which uses AzAPICall, as you know :) - from VSCode being logged in as the SPs that we use for this purpose. I ran it against 4 different tenants and I got the output/files that I expected.
I should probably add that we use Enterprise Applications in the different tenants. They are based on App Registrations which are the ones that I used for credentials when I tested it locally.

**Comment by JulianHayward** [comment]
still odd :)
Can you create a simple pipeline that only does:
```
Set-AzContext -SubscriptionId $SubscriptionId4AzContext
```

**Comment by AsbjornNielsen** [comment]
I have tried a few different combinations of Set-AzContext and build agents.

I have tried with only Set-AzContext **-SubscriptionId** as you asked for. It did not work unfortunately.
I then tried Set-AzContext with only **-TenantId** and then another Set-AzContext with only **-SusbcriptionId**, which didn't work.
I then tried Set-AzContext **-TenantId -SubscriptionId** which worked

![image](https://github.com/JulianHayward/AzAPICall/assets/9654937/acf953e9-b2e5-4a42-a519-4d0f6f764184)

In AzAPICallFunctions.ps1, I imagine this would fix it:
![image](https://github.com/JulianHayward/AzAPICall/assets/9654937/6f42115d-6857-48a9-8175-0b76ca359e2f)

**Comment by JulianHayward** [comment]
can you please do one more verification in the pipeline? Can we grab the tenantId from the current context for the set-AzContext?
```
(Get-AzContext).Tenant.Id
```

**Comment by AsbjornNielsen** [comment]
I tried all 3 combinations that I mentioned earlier. I tried all 3 with both self-hosted and default agent - same results on both agent types.

Set-AzContext -TenantId $TenantId -SubscriptionId $ManagementSubscriptionId
Works
![SetAzContext1](https://github.com/JulianHayward/AzAPICall/assets/9654937/34ccaf4a-db5f-4476-92b8-e99807489f1e)

Set-AzContext -SubscriptionId $ManagementSubscriptionId
It looks for a subId that doesn't exist in this tenant and obviously fails.
![SetAzContext2](https://github.com/JulianHayward/AzAPICall/assets/9654937/066bd804-c467-4bfc-a3e5-9e32e8adfd2b)


Set-AzContext -TenantId $TenantId
then
Set-AzContext -SubscriptionId $ManagementSubscriptionId
This last example is reflective of how our actual pipeline runs and fails. Before running AzGovVizParallel.ps1, we set the context to the desired tenant. AzGovVizParallel.ps1 then calls AzAPICall which uses Set-AzContext -SubscriptionId
![SetAzContext3](https://github.com/JulianHayward/AzAPICall/assets/9654937/9a2648c2-4b8c-4e27-a47e-a4e7320f4fdb)

**Comment by JulianHayward** [comment]
@AsbjornNielsen so we cannot take the tenantId from the current context.
Would it be possible to use different Service Connections?
Else I think AzGovViz and the AzAPICall require an update: introduce a new parameter `-TenantId4AzContext`.
Can you ping me on LinkedIn, so we can take it offline?

**Comment by JulianHayward** [comment]
@AsbjornNielsen @paulgrimley
using multiple service connections seems to solve the issue. From my point of view that is a valid working procedure vs. updating AzAPICall and AzGovViz with a `-TenantId4AzContext` parameter.

**Comment by AsbjornNielsen** [comment]
I have tested that one service connection per tenant does indeed work. However, it is not a sustainable solution for us as we manage multiple tenants and will keep adding more tenants, as we are a managed service provider.

All of our other repositories/pipelines use their respective single service connection and we would like to keep that consistency. If the addition of the ```-TenantId4AzContext``` parameter is not an option, we will have to make forks in both AzAPICall and AzGovViz and maintain them.

**Comment by JulianHayward** [comment]
@AsbjornNielsen if you have a neat technical implementation to control the the tenant for the context then please feel free to create PRs per product

**Comment by AsbjornNielsen** [comment]
Sounds good :) I will see if I can put something together

**Comment by AsbjornNielsen** [comment]
Hi Julian.
I have made a couple of PRs.
For testing I didn't want to publish my own version of AzAPICall to PS Gallery, so I had to copy/paste/slightlyModify the code into a branch of the repository I run AzGovViz from. However, it worked as I had hoped.
Please let me know what you think.

AzAPICall
https://github.com/JulianHayward/AzAPICall/pull/44

AzGovViz
https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/pull/209

**Comment by JulianHayward** [comment]
@AsbjornNielsen I´ve pushed AzAPICall 1.1.77 to the PSGal - can you please check/verify?

**Comment by AsbjornNielsen** [comment]
I have bumped the AzAPICall version to 1.1.77 in my AzGovViz branch. I tested by pulling my AzGovViz branch instead of the main/master one and the pipeline ran successfully

**Comment by AsbjornNielsen** [comment]
Unfortunately, I'm getting the "Please provide a valid tenant or a valid subscription." error again.

I'm quite sure this was introudced with commit "80856aa" which adds an if-else block starting at line 1882 (as of 7a19665) in AzApiCallFunctions.ps1. I run into the else part where Set-AzContext is called without the -TenantId4AzContext parameter (line 1902 in 7a19665). Why I end in the else, I don't know.

As you can see on the below image, it gets to "Az context is already set to TenantId" (line 1897), then fails at setting the context (line 1902) and throws at (line 1919).

![image](https://github.com/JulianHayward/AzAPICall/assets/9654937/86dfaa17-fb55-4030-83f4-ced0f1a7c4a1)

**Comment by JulianHayward** [comment]
@AsbjornNielsen so you are suggesting to change line 1902 (and potentially 1892) to:
```
$null = Set-AzContext -SubscriptionId $SubscriptionId4AzContext -TenantId $TenantId4AzContext -ErrorAction Stop
```

**Comment by AsbjornNielsen** [comment]
Yes, I'm quite sure that adding ```-TenantId $TenantId4AzContext``` would fix my problem.
You are right, it should probably be added to 1892 as well or I might encounter it again at a later point.

**Comment by JulianHayward** [comment]
okay, please test with 1.1.79

**Comment by AsbjornNielsen** [comment]
I did a .replace($oldVersion, $newVersion) to switch to 1.1.79 and it worked on the problematic tenant.
The runIdentifier is: BBF8FD22939B2626B33A8DC21AE613706F026EB171F8DD94825E78794EE259EF80BE0432075E0E1FD712B07C9AF95DB62AC64A20ED5DD0E160B0E87443F853DD

**Comment by AsbjornNielsen** [comment]
It looks to my like the issue is solved now. Thanks for the cooperation! :)
