### ISSUE TITLE
Requests which only depends on the status code of an API call aren't supported

### ISSUE THREAD

**Issue by kaiaschulz** [JulianHayward/AzAPICall#5]
Now, we would like to only use the Azure APIs instead of AZ cmdlets. 
Regarding to this, several APIs will be tested.

One, which isn't working in the main branch, is checking the existence of an resource group:
[https://docs.microsoft.com/en-us/rest/api/resources/resourcegroups/checkexistence](https://docs.microsoft.com/en-us/rest/api/resources/resourcegroups/checkexistence)

As explained in the article the statuscode (_204_) of the API call or the statuscode (_404 => NotFound_) of the error in the catch is needed.
Regarding to this, an add `$listenOn`-Parameter like "StatusCode" is needed.
Additionally, not only the status code 200 is accepted and within the catch-part of the API call a status code check is needed as well.

Within the branch "_user/kaiaschulz/mgmtapi-rg_check_" a first test was successful.

**Comment by Timsto** [comment]
i will have a look on this.  the problem would be that different endpoints will report something that could break your problem. but i see that the best way will be :)

**Comment by kaiaschulz** [comment]
I checked the used API documentations and these are the existence checks which I found:

### Management Endpoint

---

[https://docs.microsoft.com/en-us/rest/api/resources/deployments/checkexistence
](https://docs.microsoft.com/en-us/rest/api/resources/deployments/checkexistence)

_HEAD https://management.azure.com/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.Resources/deployments/{deploymentName}?api-version=2020-10-01_

---

[https://docs.microsoft.com/en-us/rest/api/resources/deployments/checkexistenceatmanagementgroupscope
](https://docs.microsoft.com/en-us/rest/api/resources/deployments/checkexistenceatmanagementgroupscope)
_HEAD https://management.azure.com/providers/Microsoft.Management/managementGroups/{groupId}/providers/Microsoft.Resources/deployments/{deploymentName}?api-version=2020-10-01_

---

[https://docs.microsoft.com/en-us/rest/api/resources/deployments/checkexistenceatscope
](https://docs.microsoft.com/en-us/rest/api/resources/deployments/checkexistenceatscope)
_HEAD https://management.azure.com/{scope}/providers/Microsoft.Resources/deployments/{deploymentName}?api-version=2020-10-01_

---

[https://docs.microsoft.com/en-us/rest/api/resources/deployments/checkexistenceatsubscriptionscope
](https://docs.microsoft.com/en-us/rest/api/resources/deployments/checkexistenceatsubscriptionscope)
_HEAD https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Resources/deployments/{deploymentName}?api-version=2020-10-01_

---

[https://docs.microsoft.com/en-us/rest/api/resources/deployments/checkexistenceattenantscope
](https://docs.microsoft.com/en-us/rest/api/resources/deployments/checkexistenceattenantscope)
_HEAD https://management.azure.com/providers/Microsoft.Resources/deployments/{deploymentName}?api-version=2020-10-01_

---

[https://docs.microsoft.com/en-us/rest/api/resources/resourcegroups/checkexistence
](https://docs.microsoft.com/en-us/rest/api/resources/resourcegroups/checkexistence)
_HEAD https://management.azure.com/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}?api-version=2020-10-01_

---

[https://docs.microsoft.com/en-us/rest/api/resources/resources/checkexistence
](https://docs.microsoft.com/en-us/rest/api/resources/resources/checkexistence)
_HEAD https://management.azure.com/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}?api-version=2020-10-01_

---

[https://docs.microsoft.com/en-us/rest/api/resources/resources/checkexistencebyid
](https://docs.microsoft.com/en-us/rest/api/resources/resources/checkexistencebyid)
_HEAD https://management.azure.com/{resourceId}?api-version=2020-10-01_

---

### RESPONSES
**204** 
No Content		

**404** 
Not Found		

**Other Status Codes**
Error response describing why the operation failed.

---

The behaviour and responses for an existence check should be equal for the management-API.
The way of checking availability with the API is already working with the previous implementation.

For "Key Vault"- or "Graph"-API the requests are "GET"- instead of "HEAD"-method's.
Regarding to this, the responses are also different.

Thanks :)

**Comment by Timsto** [comment]
Hey,  i added support for HEAD request.  But need to be carefull with it.   Response if something exist or not are different in the backend.   so acutally i build in that you got a String back if something exist and a `THROW` if the resource didnt exist.  But lets disscuss about it.   I see that you can also use a `GET` on the Ressource and also got the infromation if it exist.  so that could maybe also be a workaround for you.
