### ISSUE TITLE
How to build the Module for use

### ISSUE THREAD

**Issue by BrooksV** [JulianHayward/AzAPICall#6]
I cloned the Repo using VS Code to C:\Git_Ext
In my script, I did a:
`Import-Module -Scope Local -Name 'C:\Git_Ext\AzAPICall\AzApiCall\AzApiCall.psm1'`
and got this error:

> Get-PSFConfigValue : The term 'Get-PSFConfigValue' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct 
> and try again.

**Do we have any instructions on how to build the Module so I can import locally vs from a gallery?**

**Comment by Timsto** [comment]
currently you need the 'PSFramework' module.   i the future i think of a replacement.   normally it should be a required module.  i will check it.

**Comment by Timsto** [comment]
mhh,  it is a part of the PSframework which is a required module.   not sure why PS didnt throw you an error while importing azapicall

**Comment by Timsto** [comment]
got the problem, was a missing ","...like always.   push it this night to dev

**Comment by JulianHayward** [comment]
@Timsto hmm, do we really rely on the PSFramework?

**Comment by Timsto** [comment]
@JulianHayward  currently some command inside the module implementation rely on it.  but we can discuss about it.   i like some ways around output handling.   lets discuss it next meeting
